name: Linter

on: [pull_request]

permissions:
  checks: write
  contents: write
  issues: write
  pull-requests: write


jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: eslint
        uses: reviewdog/action-eslint@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review
          eslint_flags: '**/*.{js,ts,vue}'
          level: error # 指摘が発生したらjobを失敗扱いにする
